"""
Deployment configuration generator for post-training handoff.

Generates ready-to-use config files for popular LLM serving runtimes.
Does NOT start or manage servers; output is consumed by the target tool.

Supported targets:
  ollama      — Modelfile for ``ollama create``
  vllm        — engine config YAML for ``python -m vllm.entrypoints.api_server``
  tgi         — docker-compose.yaml for HuggingFace TGI
  hf-endpoints — JSON spec for HuggingFace Inference Endpoints API

Usage (programmatic):
    from forgelm.deploy import generate_deploy_config
    result = generate_deploy_config("./outputs/my_run", "ollama", "./Modelfile")

Usage (CLI):
    forgelm deploy ./outputs/my_run --target ollama --output ./Modelfile
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from typing import Optional

import yaml

logger = logging.getLogger("forgelm.deploy")

SUPPORTED_TARGETS = frozenset({"ollama", "vllm", "tgi", "hf-endpoints"})

# Default filenames per target when --output is not specified
_DEFAULT_FILENAMES = {
    "ollama": "Modelfile",
    "vllm": "vllm_config.yaml",
    "tgi": "docker-compose.yaml",
    "hf-endpoints": "hf_endpoint.json",
}


@dataclass
class DeployResult:
    """Result of a ``generate_deploy_config`` call."""

    success: bool
    target: str
    output_path: Optional[str] = None
    content: Optional[str] = None  # The generated config text
    error: Optional[str] = None


@dataclass
class SamplingOptions:
    """Sampling defaults for runtimes that bake them into the config (Ollama)."""

    temperature: float = 0.7
    top_k: int = 50
    top_p: float = 0.9


@dataclass
class HFEndpointsOptions:
    """All HuggingFace Inference Endpoints knobs that the JSON spec accepts."""

    task: str = "text-generation"
    instance_size: str = "x2"
    instance_type: str = "nvidia-a10g"
    region: str = "us-east-1"
    framework: str = "pytorch"
    vendor: str = "aws"


# ---------------------------------------------------------------------------
# Per-target generators
# ---------------------------------------------------------------------------


def _ollama_modelfile(
    model_path: str,
    system_prompt: Optional[str],
    max_length: int,
    temperature: float,
    top_k: int,
    top_p: float,
) -> str:
    """Generate an Ollama Modelfile."""
    lines = [
        f"FROM {model_path}",
        "",
        f"PARAMETER temperature {temperature}",
        f"PARAMETER top_k {top_k}",
        f"PARAMETER top_p {top_p}",
        f"PARAMETER num_ctx {max_length}",
        "",
    ]
    if system_prompt:
        # Escape any double quotes in the system prompt
        safe_prompt = system_prompt.replace('"', '\\"')
        lines.append(f'SYSTEM "{safe_prompt}"')
        lines.append("")

    lines += [
        "# Generated by ForgeLM deploy",
        "# Run: ollama create my-model -f Modelfile",
        "#      ollama run my-model",
    ]
    return "\n".join(lines) + "\n"


def _vllm_config(
    model_path: str,
    max_length: int,
    trust_remote_code: bool,
    gpu_memory_utilization: float,
    dtype: str,
) -> str:
    """Generate a vLLM engine config YAML."""
    cfg = {
        "model": model_path,
        "max_model_len": max_length,
        "gpu_memory_utilization": gpu_memory_utilization,
        "trust_remote_code": trust_remote_code,
        "dtype": dtype,
        "# Generated by ForgeLM deploy": None,
        "# Run": "python -m vllm.entrypoints.openai.api_server --config vllm_config.yaml",
    }
    # Remove comment pseudo-keys (yaml.dump handles None as null; post-process)
    comment_keys = [k for k in cfg if k.startswith("#")]
    comments = "\n".join(k if cfg[k] is None else f"{k}: {cfg[k]}" for k in comment_keys)
    for k in comment_keys:
        del cfg[k]

    return yaml.dump(cfg, default_flow_style=False, sort_keys=False) + "\n" + comments + "\n"


def _tgi_compose(
    model_path: str,
    max_input_length: int,
    max_total_tokens: int,
    port: int,
) -> str:
    """Generate a docker-compose.yaml for HuggingFace Text Generation Inference."""
    compose = {
        "services": {
            "tgi": {
                "image": "ghcr.io/huggingface/text-generation-inference:latest",
                "ports": [f"{port}:80"],
                "volumes": [f"{os.path.abspath(model_path)}:/data"],
                "command": (
                    f"--model-id /data --max-input-length {max_input_length} --max-total-tokens {max_total_tokens}"
                ),
                "deploy": {
                    "resources": {
                        "reservations": {"devices": [{"driver": "nvidia", "count": 1, "capabilities": ["gpu"]}]}
                    }
                },
            }
        },
    }
    header = (
        "# Generated by ForgeLM deploy\n# Run: docker compose up\n# Endpoint: http://localhost:{port}/generate\n\n"
    ).format(port=port)
    return header + yaml.dump(compose, default_flow_style=False)


def _hf_endpoints_json(
    model_path: str,
    task: str,
    instance_size: str,
    instance_type: str,
    region: str,
    framework: str,
    vendor: str = "aws",
) -> str:
    """Generate a HuggingFace Inference Endpoints API spec JSON."""
    spec = {
        "model": {
            "repository": model_path,
            "framework": framework,
            "task": task,
            "image": {"huggingface": {}},
        },
        "compute": {
            "accelerator": "gpu",
            "instanceSize": instance_size,
            "instanceType": instance_type,
            "scaling": {"minReplica": 0, "maxReplica": 1},
        },
        "cloud": {"region": region, "vendor": vendor},
        "_generated_by": "ForgeLM deploy",
        "_docs": "https://huggingface.co/docs/inference-endpoints/api_reference",
    }
    return json.dumps(spec, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_deploy_config(
    model_path: str,
    target: str,
    output_path: Optional[str] = None,
    *,
    # Shared options
    system_prompt: Optional[str] = None,
    max_length: int = 4096,
    trust_remote_code: bool = False,
    # Grouped: see SamplingOptions / HFEndpointsOptions for fields
    sampling: Optional[SamplingOptions] = None,
    hf_endpoints: Optional[HFEndpointsOptions] = None,
    # vLLM-specific
    gpu_memory_utilization: float = 0.90,
    dtype: str = "bfloat16",
    # TGI-specific
    port: int = 8080,
) -> DeployResult:
    """Generate a deployment configuration file for the given *target* runtime.

    Args:
        model_path: Local directory of a fine-tuned / merged model.
        target: One of ``ollama``, ``vllm``, ``tgi``, ``hf-endpoints``.
        output_path: File path to write.  Defaults to a target-appropriate
            filename in the current working directory.
        system_prompt: Optional system prompt to embed (Ollama Modelfile only).
        max_length: Context window length.
        trust_remote_code: Passed to vLLM config.
        sampling: Sampling defaults bundle (temperature/top_k/top_p) used by
            Ollama. Defaults to ``SamplingOptions()`` when ``None``.
        hf_endpoints: HF-Endpoints knobs (task/instance_size/instance_type/
            region/framework/vendor). Defaults to ``HFEndpointsOptions()``
            when ``None``.
        gpu_memory_utilization: vLLM GPU utilisation fraction.
        dtype: Compute dtype string (vLLM).
        port: Host port for the TGI container.

    Returns:
        :class:`DeployResult` with the generated content and output path.
    """
    sampling = sampling or SamplingOptions()
    hf_endpoints = hf_endpoints or HFEndpointsOptions()

    target = target.lower()
    if target not in SUPPORTED_TARGETS:
        return DeployResult(
            success=False,
            target=target,
            error=f"Unsupported target '{target}'. Choose from: {', '.join(sorted(SUPPORTED_TARGETS))}",
        )

    # tgi mounts model_path as a docker volume; ollama Modelfile FROM expects
    # either a local directory or an Ollama-registry name. An HF Hub ID like
    # "meta-llama/Llama-3-8B" silently produces a broken config the user only
    # discovers at `docker compose up` / `ollama create` time.
    if target in {"tgi", "ollama"} and not os.path.isdir(model_path):
        return DeployResult(
            success=False,
            target=target,
            error=(
                f"target='{target}' requires a local model directory but '{model_path}' is not a directory. "
                "Pass the path to a fine-tuned/merged model on disk (HF Hub IDs are not supported for this target)."
            ),
        )

    if output_path is None:
        output_path = _DEFAULT_FILENAMES[target]

    try:
        if target == "ollama":
            content = _ollama_modelfile(
                model_path, system_prompt, max_length, sampling.temperature, sampling.top_k, sampling.top_p
            )
        elif target == "vllm":
            content = _vllm_config(model_path, max_length, trust_remote_code, gpu_memory_utilization, dtype)
        elif target == "tgi":
            max_total = max_length + 512  # generous output budget
            content = _tgi_compose(model_path, max_length, max_total, port)
        else:  # hf-endpoints
            content = _hf_endpoints_json(
                model_path,
                hf_endpoints.task,
                hf_endpoints.instance_size,
                hf_endpoints.instance_type,
                hf_endpoints.region,
                hf_endpoints.framework,
                hf_endpoints.vendor,
            )

        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info("Deploy config written to %s", output_path)
        return DeployResult(success=True, target=target, output_path=output_path, content=content)

    except Exception as e:
        logger.error("Failed to generate deploy config for target '%s': %s", target, e)
        return DeployResult(success=False, target=target, error=str(e))
