"""Automatic model card generation for fine-tuned models.

Generates a HuggingFace-compatible README.md (model card) with training
configuration, metrics, dataset info, and evaluation results.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger("forgelm.model_card")

MODEL_CARD_TEMPLATE = """---
language:
- en
tags:
- forgelm
- fine-tuned
- lora
{extra_tags}
base_model: {base_model}
---

# {model_name}

Fine-tuned with [ForgeLM](https://github.com/cemililik/ForgeLM) — config-driven LLM fine-tuning toolkit.

## Training Details

| Parameter | Value |
|-----------|-------|
| Base Model | `{base_model}` |
| Backend | {backend} |
| Fine-Tuning Method | {method} |
| LoRA Rank (r) | {lora_r} |
| LoRA Alpha | {lora_alpha} |
| DoRA | {use_dora} |
| Target Modules | {target_modules} |
| Epochs | {epochs} |
| Batch Size | {batch_size} |
| Learning Rate | {learning_rate} |
| Max Sequence Length | {max_length} |
| Quantization | {quantization} |
| Dataset | `{dataset}` |
| Training Date | {date} |

## Metrics

{metrics_table}

{benchmark_section}

{safety_section}

## Configuration

This model was trained using the following ForgeLM YAML configuration:

```yaml
{config_yaml}
```

## Usage

```python
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

base_model = AutoModelForCausalLM.from_pretrained("{base_model}")
model = PeftModel.from_pretrained(base_model, "{model_path}")
tokenizer = AutoTokenizer.from_pretrained("{model_path}")
```

---
*Generated by ForgeLM v{version}*
"""


def _build_metrics_table(metrics: Dict[str, float]) -> str:
    """Render the eval metrics dict as a markdown table (or a placeholder)."""
    if not metrics:
        return "*No metrics available.*"
    lines = ["| Metric | Value |", "|--------|-------|"]
    for key, value in sorted(metrics.items()):
        if not key.startswith("benchmark/"):
            lines.append(f"| {key} | {value:.4f} |")
    return "\n".join(lines)


def _build_benchmark_section(
    benchmark_scores: Optional[Dict[str, float]],
    benchmark_average: Optional[float],
) -> str:
    """Render the benchmark section, empty string when no benchmark was run."""
    if not benchmark_scores:
        return ""
    lines = ["## Benchmark Results", "", "| Task | Score |", "|------|-------|"]
    for task, score in sorted(benchmark_scores.items()):
        lines.append(f"| {task} | {score:.4f} |")
    if benchmark_average is not None:
        lines.append(f"| **Average** | **{benchmark_average:.4f}** |")
    return "\n".join(lines)


def _build_safety_section(
    safety_cfg: Any,
    safety_score: Optional[float],
    safety_categories: Optional[Dict[str, int]],
) -> str:
    """Render the safety section, empty string when safety eval was disabled."""
    if not (safety_cfg and safety_cfg.enabled):
        return ""
    lines = [
        "## Safety Evaluation",
        "",
        f"- **Scoring method:** {getattr(safety_cfg, 'scoring', 'binary')}",
        f"- **Classifier:** `{safety_cfg.classifier}`",
    ]
    if safety_score is not None:
        lines.append(f"- **Safety score:** {safety_score:.4f}")
    if safety_categories:
        lines.append("- **Harm categories detected:**")
        for cat, count in sorted(safety_categories.items()):
            lines.append(f"  - {cat}: {count}")
    return "\n".join(lines)


def _format_method(config: Any, trainer_type: str) -> str:
    """Compose the human-readable training-method string for the card."""
    method = "QLoRA (4-bit)" if config.model.load_in_4bit else "LoRA"
    if trainer_type != "sft":
        method += f" + {trainer_type.upper()}"
    if config.lora.use_dora:
        method += " + DoRA"
    return method


def _build_extra_tags(config: Any, trainer_type: str, safety_cfg: Any) -> str:
    """Compose the YAML-frontmatter tag list."""
    tags = []
    if config.lora.use_dora:
        tags.append("- dora")
    if config.model.load_in_4bit:
        tags.append("- qlora")
    if trainer_type != "sft":
        tags.append(f"- {trainer_type}")
    if safety_cfg and safety_cfg.enabled:
        tags.append("- safety-evaluated")
    return "\n".join(tags)


def generate_model_card(
    config: Any,
    metrics: Dict[str, float],
    final_path: str,
    benchmark_scores: Optional[Dict[str, float]] = None,
    benchmark_average: Optional[float] = None,
    safety_score: Optional[float] = None,
    safety_categories: Optional[Dict[str, int]] = None,
) -> str:
    """Generate a model card and save it to the final model directory.

    Returns the path to the generated model card.
    """
    import yaml

    from forgelm import __version__

    eval_cfg = getattr(config, "evaluation", None)
    safety_cfg = eval_cfg.safety if (eval_cfg and hasattr(eval_cfg, "safety") and eval_cfg.safety) else None
    trainer_type = getattr(config.training, "trainer_type", "sft")

    metrics_table = _build_metrics_table(metrics)
    benchmark_section = _build_benchmark_section(benchmark_scores, benchmark_average)
    safety_section = _build_safety_section(safety_cfg, safety_score, safety_categories)
    method = _format_method(config, trainer_type)
    extra_tags_str = _build_extra_tags(config, trainer_type, safety_cfg)

    # Serialize config to YAML (excluding sensitive fields)
    config_dict = config.model_dump(exclude={"auth", "webhook", "monitoring"})
    config_yaml = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)

    card = MODEL_CARD_TEMPLATE.format(
        model_name=config.model.name_or_path.split("/")[-1] + "_finetune",
        base_model=config.model.name_or_path,
        backend=config.model.backend,
        method=method,
        lora_r=config.lora.r,
        lora_alpha=config.lora.alpha,
        use_dora=config.lora.use_dora,
        target_modules=", ".join(config.lora.target_modules),
        epochs=config.training.num_train_epochs,
        batch_size=config.training.per_device_train_batch_size,
        learning_rate=config.training.learning_rate,
        max_length=config.model.max_length,
        quantization="4-bit NF4" if config.model.load_in_4bit else "None",
        dataset=config.data.dataset_name_or_path,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        metrics_table=metrics_table,
        benchmark_section=benchmark_section,
        safety_section=safety_section,
        config_yaml=config_yaml,
        model_path=final_path,
        version=__version__,
        extra_tags=extra_tags_str,
    )

    card_path = os.path.join(final_path, "README.md")
    os.makedirs(final_path, exist_ok=True)
    with open(card_path, "w") as f:
        f.write(card)

    logger.info("Model card saved to %s", card_path)
    return card_path
