"""Automatic model card generation for fine-tuned models.

Generates a HuggingFace-compatible README.md (model card) with training
configuration, metrics, dataset info, and evaluation results.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger("forgelm.model_card")

MODEL_CARD_TEMPLATE = """---
language:
- en
tags:
- forgelm
- fine-tuned
- lora
{extra_tags}
base_model: {base_model}
---

# {model_name}

Fine-tuned with [ForgeLM](https://github.com/cemililik/ForgeLM) — config-driven LLM fine-tuning toolkit.

## Training Details

| Parameter | Value |
|-----------|-------|
| Base Model | `{base_model}` |
| Backend | {backend} |
| Fine-Tuning Method | {method} |
| LoRA Rank (r) | {lora_r} |
| LoRA Alpha | {lora_alpha} |
| DoRA | {use_dora} |
| Target Modules | {target_modules} |
| Epochs | {epochs} |
| Batch Size | {batch_size} |
| Learning Rate | {learning_rate} |
| Max Sequence Length | {max_length} |
| Quantization | {quantization} |
| Dataset | `{dataset}` |
| Training Date | {date} |

## Metrics

{metrics_table}

{benchmark_section}

{safety_section}

## Configuration

This model was trained using the following ForgeLM YAML configuration:

```yaml
{config_yaml}
```

## Usage

```python
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

base_model = AutoModelForCausalLM.from_pretrained("{base_model}")
model = PeftModel.from_pretrained(base_model, "{model_path}")
tokenizer = AutoTokenizer.from_pretrained("{model_path}")
```

---
*Generated by ForgeLM v{version}*
"""


def generate_model_card(
    config: Any,
    metrics: Dict[str, float],
    final_path: str,
    benchmark_scores: Optional[Dict[str, float]] = None,
    benchmark_average: Optional[float] = None,
    safety_score: Optional[float] = None,
    safety_categories: Optional[Dict[str, int]] = None,
) -> str:
    """Generate a model card and save it to the final model directory.

    Returns the path to the generated model card.
    """
    import yaml

    from forgelm import __version__

    # Build metrics table
    if metrics:
        metrics_lines = ["| Metric | Value |", "|--------|-------|"]
        for key, value in sorted(metrics.items()):
            if not key.startswith("benchmark/"):
                metrics_lines.append(f"| {key} | {value:.4f} |")
        metrics_table = "\n".join(metrics_lines)
    else:
        metrics_table = "*No metrics available.*"

    # Build benchmark section
    benchmark_section = ""
    if benchmark_scores:
        lines = ["## Benchmark Results", "", "| Task | Score |", "|------|-------|"]
        for task, score in sorted(benchmark_scores.items()):
            lines.append(f"| {task} | {score:.4f} |")
        if benchmark_average is not None:
            lines.append(f"| **Average** | **{benchmark_average:.4f}** |")
        benchmark_section = "\n".join(lines)

    # Build safety section
    safety_section = ""
    eval_cfg = getattr(config, "evaluation", None)
    safety_cfg = eval_cfg.safety if (eval_cfg and hasattr(eval_cfg, "safety") and eval_cfg.safety) else None
    if safety_cfg and safety_cfg.enabled:
        safety_lines = [
            "## Safety Evaluation",
            "",
            f"- **Scoring method:** {getattr(safety_cfg, 'scoring', 'binary')}",
            f"- **Classifier:** `{safety_cfg.classifier}`",
        ]
        if safety_score is not None:
            safety_lines.append(f"- **Safety score:** {safety_score:.4f}")
        if safety_categories:
            safety_lines.append("- **Harm categories detected:**")
            for cat, count in sorted(safety_categories.items()):
                safety_lines.append(f"  - {cat}: {count}")
        safety_section = "\n".join(safety_lines)

    # Determine method
    method = "QLoRA (4-bit)" if config.model.load_in_4bit else "LoRA"
    trainer_type = getattr(config.training, "trainer_type", "sft")
    if trainer_type != "sft":
        method += f" + {trainer_type.upper()}"
    if config.lora.use_dora:
        method += " + DoRA"

    # Extra tags
    extra_tags = []
    if config.lora.use_dora:
        extra_tags.append("- dora")
    if config.model.load_in_4bit:
        extra_tags.append("- qlora")
    if trainer_type != "sft":
        extra_tags.append(f"- {trainer_type}")
    if safety_cfg and safety_cfg.enabled:
        extra_tags.append("- safety-evaluated")
    extra_tags_str = "\n".join(extra_tags)

    # Serialize config to YAML (excluding sensitive fields)
    config_dict = config.model_dump(exclude={"auth", "webhook", "monitoring"})
    config_yaml = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)

    card = MODEL_CARD_TEMPLATE.format(
        model_name=config.model.name_or_path.split("/")[-1] + "_finetune",
        base_model=config.model.name_or_path,
        backend=config.model.backend,
        method=method,
        lora_r=config.lora.r,
        lora_alpha=config.lora.alpha,
        use_dora=config.lora.use_dora,
        target_modules=", ".join(config.lora.target_modules),
        epochs=config.training.num_train_epochs,
        batch_size=config.training.per_device_train_batch_size,
        learning_rate=config.training.learning_rate,
        max_length=config.model.max_length,
        quantization="4-bit NF4" if config.model.load_in_4bit else "None",
        dataset=config.data.dataset_name_or_path,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        metrics_table=metrics_table,
        benchmark_section=benchmark_section,
        safety_section=safety_section,
        config_yaml=config_yaml,
        model_path=final_path,
        version=__version__,
        extra_tags=extra_tags_str,
    )

    card_path = os.path.join(final_path, "README.md")
    os.makedirs(final_path, exist_ok=True)
    with open(card_path, "w") as f:
        f.write(card)

    logger.info("Model card saved to %s", card_path)
    return card_path
