"""Wizard state, persistence, summary + step-diff helpers.

Persistence (Phase 22 / G6): state snapshot is YAML at
``$XDG_CACHE_HOME/forgelm/wizard_state.yaml`` (or
``~/.cache/forgelm/wizard_state.yaml`` when XDG is unset).  Schema
versioned so a future shape change can clear stale snapshots cleanly.
"""

from __future__ import annotations

import logging
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

import yaml

from ._io import _print

logger = logging.getLogger("forgelm.wizard")


# ---------------------------------------------------------------------------
# Wizard-wide defaults — schema-derived single source of truth (F1 /
# review-cycle 3).
#
# Values come from ``forgelm/wizard/_defaults.json``, generated by
# ``tools/generate_wizard_defaults.py`` from Pydantic fields tagged
# ``json_schema_extra={"wizard": True}``.  The CI guard
# ``tools/check_wizard_defaults_sync.py`` rejects manual drift between
# the schema and the shipped JSON, so a schema default change without
# regenerating fails at PR time rather than producing a silent skew.
#
# The hardcoded fallbacks below are last-resort values that match the
# schema today — they activate only when the JSON is missing entirely
# (e.g., a broken ``pip install`` that lost the package data).  Keeping
# them in sync with the schema is a soft contract: drift here is OK
# because the JSON is the canonical source.
# ---------------------------------------------------------------------------


def _load_defaults() -> Dict[str, Dict[str, Any]]:
    """Read the schema-derived wizard defaults from package data.

    Falls back to an empty dict when the JSON is absent (broken pip
    install, slim test environment) — the module-level ``DEFAULT_*``
    constants then resolve to their hardcoded sentinel values.
    """
    import json

    try:
        from importlib.resources import files

        path = files("forgelm.wizard").joinpath("_defaults.json")
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        # Source-only environment without the JSON — fall back to
        # hardcoded values below.  Logged only in debug to keep the
        # wizard's startup quiet.
        logger.debug("forgelm/wizard/_defaults.json not found; using hardcoded fallbacks.")
        return {}
    if not isinstance(data, dict):
        logger.warning("forgelm/wizard/_defaults.json does not parse as a JSON object; ignored.")
        return {}
    # Strip the leading ``"//"`` comment keys the generator emits.
    return {k: v for k, v in data.items() if not k.startswith("//")}


_DEFAULTS = _load_defaults()


def _default(section: str, key: str, fallback: Any) -> Any:
    """Return the schema-derived value; warn on schema↔fallback drift.

    B5 (review-cycle 3): the hardcoded fallbacks below act as a
    second source of truth that activates when the shipped JSON is
    missing.  When BOTH are present and disagree, the schema/JSON is
    canonical (we return that value), but we emit a WARNING so the
    drift surfaces in CI logs — that's the trigger for a contributor
    to update the fallback literal in ``_state.py`` to match.

    No-op on the happy path: when ``_DEFAULTS`` is empty (slim install)
    the fallback wins silently; when both agree the WARNING never
    fires.
    """
    block = _DEFAULTS.get(section)
    if not isinstance(block, dict):
        return fallback
    value = block.get(key)
    if value is None:
        return fallback
    if value != fallback:
        logger.warning(
            "Wizard default fallback drift: %s.%s schema-derived=%r hardcoded fallback=%r — "
            "update the hardcoded literal in forgelm/wizard/_state.py to match.",
            section,
            key,
            value,
            fallback,
        )
    return value


DEFAULT_MAX_LENGTH: int = _default("model", "max_length", 2048)
DEFAULT_LORA_R: int = _default("lora", "r", 8)
DEFAULT_LORA_ALPHA: int = _default("lora", "alpha", 2 * DEFAULT_LORA_R)
DEFAULT_DROPOUT: float = _default("lora", "dropout", 0.1)
DEFAULT_EPOCHS: int = _default("training", "num_train_epochs", 3)
DEFAULT_BATCH_SIZE: int = _default("training", "per_device_train_batch_size", 4)
DEFAULT_LR: float = _default("training", "learning_rate", 2e-5)
DEFAULT_GRAD_ACCUM: int = _default("training", "gradient_accumulation_steps", 2)

# Curated popular-model presets.  This list and the
# ``USE_CASE_PRESETS`` in ``site/js/wizard.js`` are intentionally kept
# in lockstep — the operator using both surfaces sees the same
# recommended models.
POPULAR_MODELS: List[str] = [
    "meta-llama/Llama-3.1-8B-Instruct",
    "Qwen/Qwen2.5-7B-Instruct",
    "mistralai/Mistral-7B-Instruct-v0.3",
    "microsoft/Phi-3-mini-4k-instruct",
    "HuggingFaceTB/SmolLM2-1.7B-Instruct",
]


TARGET_MODULE_PRESETS: Dict[str, List[str]] = {
    "standard": ["q_proj", "v_proj"],
    "extended": ["q_proj", "k_proj", "v_proj", "o_proj"],
    "full": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
}


# Common dataset-format hints for preference-based trainers
# (DPO/SimPO/ORPO).
_PREFERENCE_COLUMNS_HINT = "Columns: prompt, chosen, rejected"


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


# Bumped whenever the on-disk wizard-state shape changes.  Version
# mismatches are silently ignored (treated as "no resume available").
#
# This number is the CLI-side wizard's serialised resume-state version.
# It is intentionally independent of the in-browser wizard's
# ``site/js/wizard.js::STATE_VERSION`` (currently 3 at time of writing):
# the two surfaces persist to entirely different stores (XDG cache JSON
# here vs. browser ``localStorage`` there) and bump on schedules tied to
# their own state-shape evolution, so a number drift between them is
# normal and not a synchronisation bug.
_STATE_VERSION = 1


def _wizard_state_dir() -> Path:
    """Return the directory the wizard persists its state under.

    Honours ``XDG_CACHE_HOME`` per the XDG Base Directory spec; falls
    back to ``~/.cache/forgelm`` when unset.  The directory is created
    on first write — no side effects on plain reads.
    """
    xdg = os.environ.get("XDG_CACHE_HOME", "").strip()
    base = Path(xdg).expanduser() if xdg else Path.home() / ".cache"
    return base / "forgelm"


def _wizard_state_path() -> Path:
    """Absolute path to ``wizard_state.yaml``."""
    return _wizard_state_dir() / "wizard_state.yaml"


def _save_wizard_state(state: Mapping[str, Any]) -> None:
    """Persist *state* to ``_wizard_state_path()``.

    Best-effort: filesystem errors (read-only home, ENOSPC, sandboxed
    container) are logged at WARNING and swallowed — the wizard's
    contract is to *produce a config*, not to guarantee resumability.
    """
    import tempfile

    target = _wizard_state_path()
    tmp_name: Optional[str] = None
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        snapshot = {"v": _STATE_VERSION, **dict(state)}
        # Atomic write: serialise to a sibling temp file, fsync, then
        # ``os.replace`` so a SIGKILL / power loss / concurrent wizard
        # process never leaves a half-written ``wizard_state.yaml``.
        # ``NamedTemporaryFile(delete=False)`` is the standard idiom for
        # this; ``os.replace`` is atomic on POSIX and Windows.
        tmp = tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=str(target.parent),
            prefix=".wizard_state.",
            suffix=".tmp",
            delete=False,
        )
        tmp_name = tmp.name
        try:
            yaml.safe_dump(snapshot, tmp, default_flow_style=False, sort_keys=False)
            tmp.flush()
            os.fsync(tmp.fileno())
        finally:
            tmp.close()
        # A3 (review-cycle 3): when ``os.replace`` fails (cross-device
        # /home overlay, EACCES, EXDEV) the temp file would otherwise
        # accumulate under ``$XDG_CACHE_HOME/forgelm/`` on every run.
        # Wrap the rename in its own try/except so the cleanup runs
        # even when the outer ``except OSError`` would otherwise just
        # log and return.
        try:
            os.replace(tmp_name, target)
            tmp_name = None  # successful rename — nothing to clean up
        except OSError:
            _safe_unlink(tmp_name)
            tmp_name = None
            raise
        # Wizard state can carry compliance metadata (provider name,
        # contact, governance fields) that operators consider sensitive.
        # ``0o600`` keeps it readable only by the operator running the
        # wizard.  Best-effort: chmod is a no-op on Windows / FAT.
        try:
            os.chmod(target, 0o600)
        except OSError:  # pragma: no cover — best-effort permission tightening
            pass
    except OSError as exc:
        logger.warning("Could not persist wizard state to %s: %s", target, exc)
    finally:
        # Defensive sweep: if any branch above left the temp file behind
        # (e.g., ``yaml.safe_dump`` raised before we even reached
        # ``os.replace``), unlink it here. ``tmp_name = None`` after
        # successful rename means this is a no-op on the happy path.
        if tmp_name is not None:
            _safe_unlink(tmp_name)


def _safe_unlink(path: str) -> None:
    """Best-effort ``os.unlink`` that swallows missing-file / permission errors."""
    try:
        os.unlink(path)
    except FileNotFoundError:  # pragma: no cover — already gone, fine
        pass
    except OSError as exc:  # pragma: no cover — read-only / permission noise
        logger.debug("Could not remove temp file %s: %s", path, exc)


def _load_wizard_state() -> Optional[Dict[str, Any]]:
    """Load a previously-saved state snapshot, returning ``None`` on miss.

    Parse errors return ``None`` — the wizard falls back to defaults
    rather than asking the operator to debug a stale snapshot.

    Version handling (F3 / review-cycle 3): older snapshots are passed
    through :data:`_STATE_MIGRATIONS` so an operator's in-flight session
    survives a wizard schema bump.  When migration fails (unknown
    version, exception in a migrator), we fall back to ``None`` rather
    than partially-migrated state.
    """
    target = _wizard_state_path()
    if not target.is_file():
        return None
    try:
        with open(target, "r", encoding="utf-8") as fh:
            snapshot = yaml.safe_load(fh)
    except (OSError, yaml.YAMLError) as exc:
        logger.warning("Could not read wizard state from %s: %s", target, exc)
        return None
    if not isinstance(snapshot, dict):
        return None
    on_disk_version = snapshot.get("v")
    if on_disk_version != _STATE_VERSION:
        migrated = _migrate_wizard_state(snapshot, on_disk_version)
        if migrated is None:
            return None
        snapshot = migrated
    snapshot.pop("v", None)
    return snapshot


# ---------------------------------------------------------------------------
# Wizard-state version-migration registry (F3 / review-cycle 3).
#
# When ``_STATE_VERSION`` is bumped, register a migrator under the
# OLD version key returning the snapshot in NEW shape.  The runtime
# loop below walks the chain (1 → 2 → 3 → … → latest) so an operator's
# wizard_state.yaml from N versions ago still resumes cleanly.
#
# Until the first real bump, the registry is empty — older snapshots
# (none yet exist) silently fall back to "no resume" via the ``return
# None`` path.  Keeping the skeleton in place means the first bump only
# adds a new entry, no plumbing rewrite.
# ---------------------------------------------------------------------------


_StateMigrator = "Callable[[Dict[str, Any]], Dict[str, Any]]"

# Empty by design.  Each entry is ``{old_version: migrator}`` where
# ``migrator(snapshot) -> snapshot`` upgrades exactly one major version.
# Example future entry::
#
#     def _migrate_v1_to_v2(snapshot: Dict[str, Any]) -> Dict[str, Any]:
#         snapshot["completed_steps"] = snapshot.pop("done_steps", [])
#         snapshot["v"] = 2
#         return snapshot
#
#     _STATE_MIGRATIONS = {1: _migrate_v1_to_v2}
_STATE_MIGRATIONS: Dict[int, Any] = {}


def _migrate_wizard_state(snapshot: Dict[str, Any], from_version: Any) -> Optional[Dict[str, Any]]:
    """Walk the migration chain from *from_version* up to ``_STATE_VERSION``.

    Returns the migrated snapshot on success, ``None`` when the chain
    cannot complete (unknown source version, missing migrator, exception
    raised by a migrator).  Fall-back to ``None`` is intentional — the
    wizard prefers "no resume" over "resume with corrupt state".
    """
    if not isinstance(from_version, int) or from_version < 1:
        return None
    if from_version > _STATE_VERSION:
        # Snapshot from a NEWER wizard than the running binary — never
        # downgrade.  Operator probably switched to an older virtualenv;
        # safer to start fresh than guess-strip new fields.
        logger.info(
            "Wizard state v=%s newer than running v=%s; ignoring snapshot.",
            from_version,
            _STATE_VERSION,
        )
        return None
    current = snapshot
    version = from_version
    while version != _STATE_VERSION:
        migrator = _STATE_MIGRATIONS.get(version)
        if migrator is None:
            logger.warning(
                "No migrator registered for wizard state v=%s; cannot resume.",
                version,
            )
            return None
        try:
            current = migrator(current)
        except Exception as exc:  # noqa: BLE001 — defensive; migrators are project-internal
            logger.warning("Wizard state migration v=%s failed: %s", version, exc)
            return None
        next_version = current.get("v")
        if not isinstance(next_version, int) or next_version <= version:
            logger.warning(
                "Migrator for wizard state v=%s did not advance the version field; aborting.",
                version,
            )
            return None
        version = next_version
    return current


def _clear_wizard_state() -> None:
    """Remove a stale state snapshot, swallowing filesystem errors."""
    target = _wizard_state_path()
    try:
        if target.is_file():
            target.unlink()
    except OSError as exc:  # pragma: no cover — best-effort cleanup
        logger.warning("Could not remove wizard state at %s: %s", target, exc)


# ---------------------------------------------------------------------------
# Wizard-state dataclass — threaded through every step in the
# orchestrator.  Persisted via the helpers above.
# ---------------------------------------------------------------------------


# Sentinel for the "manual" use-case (no preselect).  Mirrored in
# ``_byod._MANUAL_USE_CASE`` for callers that want to import from
# either submodule.
_MANUAL_USE_CASE = "custom"


@dataclass
class _WizardState:
    """In-memory snapshot of every wizard answer + the partial config dict.

    Persisted after each completed step to ``wizard_state.yaml`` so a
    refresh / Ctrl-C / fresh session resumes where the operator left
    off.

    ``hardware`` is a per-run cache of :func:`forgelm.wizard._io._detect_hardware`
    (C16 / review-cycle 3): the welcome step + the post-save pre-flight
    checklist both want the GPU/VRAM/CUDA snapshot, and re-importing
    torch each time costs ~50–200 ms.  Excluded from persistence
    (``repr`` only) — the snapshot YAML never carries it.
    """

    experience: str = "expert"  # "beginner" | "expert"
    use_case: str = _MANUAL_USE_CASE
    current_step: int = 0
    completed_steps: List[str] = field(default_factory=list)
    config: Dict[str, Any] = field(default_factory=dict)
    hardware: Optional[Dict[str, Any]] = field(default=None, repr=False, compare=False)


# ---------------------------------------------------------------------------
# Step-diff preview — Phase 22 / G7.  Each step prints the keys it
# just added or changed, mirroring the web wizard's live YAML preview
# at terminal-friendly granularity.
# ---------------------------------------------------------------------------


def _flatten_dict(d: Mapping[str, Any], *, prefix: str = "") -> Dict[str, Any]:
    """Recursively flatten a dict into ``dotted.path → value`` entries."""
    out: Dict[str, Any] = {}
    for key, value in d.items():
        path = f"{prefix}.{key}" if prefix else str(key)
        if isinstance(value, Mapping):
            out.update(_flatten_dict(value, prefix=path))
        else:
            out[path] = value
    return out


def _print_step_diff(prev: Mapping[str, Any], curr: Mapping[str, Any], step_label: str) -> None:
    """Print a ``+ key.path: value`` diff for everything *curr* added vs *prev*."""
    prev_flat = _flatten_dict(prev)
    curr_flat = _flatten_dict(curr)
    added = {k: v for k, v in curr_flat.items() if k not in prev_flat}
    changed = {k: (prev_flat[k], v) for k, v in curr_flat.items() if k in prev_flat and prev_flat[k] != v}
    if not added and not changed:
        return
    _print(f"\n  Step diff ({step_label}):")
    for key in sorted(added):
        _print(f"    + {key}: {added[key]!r}")
    for key in sorted(changed):
        before, after = changed[key]
        _print(f"    ~ {key}: {before!r} → {after!r}")


# ---------------------------------------------------------------------------
# Save + summary helpers
# ---------------------------------------------------------------------------


def _atomic_yaml_write(payload: Dict[str, Any], target_path: str) -> None:
    """Serialise *payload* to *target_path* via temp file + ``os.replace``.

    Mirrors the wizard-state atomic-write pattern: a SIGKILL / power
    loss / concurrent process between the YAML dump and the rename
    cannot corrupt or truncate ``target_path``.  Critical for
    ``--wizard-start-from`` reruns where the target may be the
    operator's existing config — an interrupted plain ``open(..., "w")``
    would leave them with neither the old config nor a complete new
    one.  ``os.replace`` is atomic on POSIX and Windows (when source
    and destination live on the same filesystem, which the
    ``dir=parent`` argument below guarantees).
    """
    target = Path(target_path)
    parent = target.parent if str(target.parent) else Path(".")
    parent.mkdir(parents=True, exist_ok=True)
    tmp = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=str(parent),
        prefix=f".{target.name}.",
        suffix=".tmp",
        delete=False,
    )
    tmp_name = tmp.name
    try:
        try:
            yaml.safe_dump(payload, tmp, default_flow_style=False, sort_keys=False, allow_unicode=True)
            tmp.flush()
            os.fsync(tmp.fileno())
        finally:
            tmp.close()
        os.replace(tmp_name, target_path)
        tmp_name = None  # successful rename
    finally:
        if tmp_name is not None:
            _safe_unlink(tmp_name)


def _save_config_to_file(config: Dict[str, Any], requested_filename: str) -> str:
    """Write *config* as YAML; falls back to a unique filename on OSError.

    Atomic via temp file + ``os.replace`` (see :func:`_atomic_yaml_write`)
    so an interrupted save during a ``--wizard-start-from`` rerun
    cannot corrupt the operator's pre-existing config.

    Uses ``yaml.safe_dump`` so unknown Python objects (e.g. accidental
    ``Path`` / ``set`` leak from a collector) raise a representable
    error instead of silently emitting a Python-only ``!!python/object``
    tag that ``ForgeConfig`` then rejects on load.
    """
    try:
        _atomic_yaml_write(config, requested_filename)
        _print(f"\n  Config saved to: {requested_filename}")
        logger.info("Wizard config saved to %s", requested_filename)
        return requested_filename
    except OSError as e:
        logger.error("Could not save wizard config to %s: %s", requested_filename, e)
        _print(f"\n  Error: Could not save config to {requested_filename}: {e}")

    from datetime import datetime as _dt

    base = os.path.splitext(os.path.basename(requested_filename))[0] or "my_config"
    fallback = os.path.join(
        os.path.expanduser("~"),
        f"{base}_{_dt.now().strftime('%Y%m%d_%H%M%S')}.yaml",
    )
    try:
        _atomic_yaml_write(config, fallback)
        _print(f"  Saved to fallback location: {fallback}")
        logger.info("Wizard config saved to fallback location %s", fallback)
        return fallback
    except OSError as e:
        logger.error("Fallback wizard config save also failed (%s): %s", fallback, e)
        _print(f"  Fallback save also failed ({fallback}): {e}")
        raise


def _strategy_label(*, use_galore: bool, load_in_4bit: bool, method: str) -> str:
    """Human-readable label for the strategy summary line."""
    if use_galore:
        return "GaLore"
    base = "QLoRA" if load_in_4bit else "LoRA"
    if method != "lora":
        return f"{base} + {method.upper()}"
    return base


def _print_wizard_summary(config: Dict[str, Any]) -> None:
    """Print a multi-section summary of the resolved config + the full YAML."""
    _print("\n" + "=" * 60)
    _print("  Configuration Summary")
    _print("=" * 60)
    model = config["model"]["name_or_path"]
    backend = config["model"].get("backend", "transformers")
    load_in_4bit = config["model"].get("load_in_4bit", False)
    lora_method = config.get("lora", {}).get("method", "lora")
    use_galore = bool(config["training"].get("galore_enabled", False))
    trainer = config["training"].get("trainer_type", "sft").upper()
    lora_r = config.get("lora", {}).get("r", DEFAULT_LORA_R)
    lora_alpha = config.get("lora", {}).get("alpha", DEFAULT_LORA_ALPHA)
    dataset = config.get("data", {}).get("dataset_name_or_path", "(not set)")
    epochs = config["training"].get("num_train_epochs", DEFAULT_EPOCHS)
    batch = config["training"].get("per_device_train_batch_size", DEFAULT_BATCH_SIZE)
    output = config["training"].get("output_dir", "./checkpoints")
    _print(f"  Model:    {model}")
    _print(f"  Backend:  {backend}")
    _print(f"  Strategy: {_strategy_label(use_galore=use_galore, load_in_4bit=load_in_4bit, method=lora_method)}")
    _print(f"  Trainer:  {trainer}")
    _print(f"  LoRA:     r={lora_r}, alpha={lora_alpha}")
    _print(f"  Dataset:  {dataset}")
    _print(f"  Epochs:   {epochs}, Batch: {batch}")
    _print(f"  Output:   {output}/final_model")
    sections = [k for k in config.keys() if k not in ("model", "lora", "training", "data")]
    if sections:
        _print(f"  Extras:   {', '.join(sorted(sections))}")
    _print("\n  Full YAML preview:")
    _print("  " + "─" * 58)
    yaml_text = yaml.safe_dump(config, default_flow_style=False, sort_keys=False, allow_unicode=True)
    for line in yaml_text.splitlines():
        _print(f"  {line}")
    _print("  " + "─" * 58)


def _strip_internal_meta(config: Mapping[str, Any]) -> Dict[str, Any]:
    """Remove keys prefixed with ``_wizard_`` before writing the YAML."""
    return {k: v for k, v in config.items() if not str(k).startswith("_wizard_")}
